#!/bin/bash
umask 0023

steamcmd +force_install_dir /valheim +login anonymous +app_update 896660 -beta none validate +quit

export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970

/autopause/autopause-daemon.sh &

/usr/sbin/knockd -c /autopause/knockd-config.cfg -d

./valheim_server.x86_64 -name "" -port 2456 -world "Dedicated" -password "" -savedir /world -saveinterval 900

export LD_LIBRARY_PATH=$templdpath
